# Generated by Django 3.0.3 on 2020-02-22 14:38

from django.db import migrations
from django.template.defaultfilters import slugify


def popular_slug(apps, schema_editor):
    """
    Esta função recebe dois parametros: apps e schema_editor
    Um detalhe importante - nao podemos importar diretamente o modelo pois ele pode estar
    em uma versao mais nova no modelo de migração. Entao delegamos ao Django esta importação
    pois ele tem o controle.
    :param apps: para pegar o modelo respectivo
    :param schema_editor:
    :return:
    """
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_modulo_slug'),
    ]
    # informar a operação o que precisa fazer => chamar a função popular_slug sem ()
    operations = [
        migrations.RunPython(popular_slug)
    ]
