name: Python application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
        
    - name: Link with flake8
      run: |
        pipenv run flake8 .

    - name: Test with pytest
      run: |
        pipenv run pytest pyprg --cov=pyprg

    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "487324d0-3ff8-412b-bfca-cfa423219329"
      run: |
        pipenv run codecov